# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=255)),
                ('stared', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('link_id', models.CharField(max_length=255)),
                ('readed', models.BooleanField(default=False)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Feed')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='newsline',
            unique_together=set([('feed', 'link_id')]),
        ),
    ]
